- name: Install wezterm
  community.general.flatpak:
    name: org.wezfurlong.wezterm
    state: present

- name: Configure wezterm
  ansible.builtin.template:
    src: wezterm.lua
    dest: "/home/{{ ansible_user }}/.wezterm.lua"
    mode: "0755"

- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Download ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "/home/{{ ansible_user }}/install.sh"
    mode: "0755"

- name: Install ohmyzsh
  ansible.builtin.script:
    cmd: "/home/{{ ansible_user }}/install.sh"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/home/{{ ansible_user }}/.zsh/zsh-autosuggestions"

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "/home/{{ ansible_user }}/.zsh/zsh-syntax-highlighting"

- name: Configure zsh
  ansible.builtin.template:
    src: .zshrc
    dest: "/home/{{ ansible_user }}/.zshrc"