# ---------------------------------------------------------------------------- #
#                                    Node.js                                   #
# ---------------------------------------------------------------------------- #
- name: Download NVM
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
    dest: "/home/{{ ansible_user }}/install_nvm.sh"
    mode: "0755"

- name: Install NVM
  ansible.builtin.script:
    cmd: "/home/{{ ansible_user }}/install_nvm.sh"

- name: Reload shell
  ansible.builtin.command:
    cmd: zsh -i -c "omz reload"

- name: Install Node LTS
  ansible.builtin.command:
    cmd: zsh -i -c "nvm install node"

# ---------------------------------------------------------------------------- #
#                                    Python                                    #
# ---------------------------------------------------------------------------- #
- name: Download pyenv
  ansible.builtin.get_url:
    url: https://pyenv.run 
    dest: "/home/{{ ansible_user }}/install_pyenv.sh"
    mode: "0755"

- name: Install pyenv
  ansible.builtin.script:
    cmd: "/home/{{ ansible_user }}/install_pyenv.sh"

- name: Install pyenv-virtualenv
  ansible.builtin.git:
    repo: "https://github.com/pyenv/pyenv-virtualenv"
    dest: "/home/{{ ansible_user }}/.pyenv/plugins/pyenv-virtualenv"

- name: Install Python {{ python_version }}
  ansible.builtin.command:
    cmd: pyenv install {{ python_version }}