- name: Download NVM
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
    dest: "/home/{{ ansible_user }}/install_nvm.sh"
    mode: "0755"

- name: Install NVM
  ansible.builtin.script:
    cmd: "/home/{{ ansible_user }}/install_nvm.sh"

- name: Reload shell
  ansible.builtin.command:
    cmd: zsh -i -c "omz reload"

- name: Install Node
  ansible.builtin.command:
    cmd: zsh -i -c "nvm install {{ item }}"
  loop:
    - node # latest
    - 20
    - 18

- name: Set default Node version
  ansible.builtin.command:
    cmd: zsh -i -c "nvm alias default node"