- name: Set keyrings permissions
  ansible.builtin.command:
    cmd: install -m 00755 -d /etc/apt/keyrings
  become: true

- name: Download GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
  become: true

- name: Set GPG permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: a+r
  become: true

- name: Add Docker repository to the APT sources
  ansible.builtin.shell:
    cmd: |
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Update APT packages
  ansible.builtin.apt:
    update_cache: true
    name: "*"
    state: latest
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
  become: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin